### ISSUE TITLE
Pending Instance is not in a valid state

### ISSUE THREAD

**Issue by johnmastri** [bevacqua/grunt-ec2#15]
Not sure what the problem is here - any suggestions?

Running "ec2_assign_existing_address:i-d22c5fda:54.186.195.18" (ec2_assign_existing_address) task
Associating EC2 instance i-d22c5fda to IP 54.186.195.18
[aws] ec2 associate-address --instance-id i-d22c5fda --public-ip 54.186.195.18
Fatal error: Request to the AWS API failed with an error.
InvalidInstanceID: The pending instance 'i-d22c5fda' is not in a valid state for this operation.
    at Request.extractError 

Thanks - JoHN

**Comment by luncht1me** [comment]
I don't think you really understand what the problem is here @bevacqua 

I have the same issue. Using ec2-launch. It doesn't wait for the 'running' state before moving on to ec2-assign-existing-address. The flow of the actual ec2-launch task is flawed at this point. 

It's 2016 and I'm getting the same error. Seems harsh that two years later I need to modify your plugin's tasks.

**Comment by jingconan** [comment]
Hi Nicolás, I have sent a PR to fix this. Could you take a look at it? Feel free to let me know if you have any comment. Thanks!
